import { Link, Route, Routes, useParams } from "react-router-dom";
import { useEffect, useState, type FormEvent } from "react";
import { RoleRoute } from "../components/RoleRoute";
import { LoginPage } from "../features/auth/LoginPage";
import { useAuth } from "../lib/auth";
import { api } from "../lib/api";

type ParticipantDashboard = { user: { displayName: string }; riskProfile: { factors: string[] } | null; goals: { id: string; title: string; targetDate: string }[]; dailyChecks: { id: string; confidence: number; checkDate: string }[] };
function ParticipantHome() { const { user, logout } = useAuth(); const [dashboard, setDashboard] = useState<ParticipantDashboard | null>(null); const [error, setError] = useState(""); useEffect(() => { void api<{ participant: ParticipantDashboard }>("/api/participant/dashboard").then(({ participant }) => setDashboard(participant)).catch((e) => setError(e.message)); }, []); return <main><h1>แผนดูแลตนเอง</h1><p>ยินดีต้อนรับ {user?.displayName}</p><button onClick={() => void logout()}>ออกจากระบบ</button><p><Link to="/participant/daily-check">บันทึกประจำวัน</Link> · <Link to="/participant/goals/new">สร้างเป้าหมาย SMART</Link> · <Link to="/participant/emergency">BE-FAST ฉุกเฉิน</Link></p>{error && <p role="alert">{error}</p>}{!dashboard ? <p>กำลังโหลดข้อมูล…</p> : <><h2>ปัจจัยเสี่ยงที่ติดตาม</h2><ul>{dashboard.riskProfile?.factors.map((factor) => <li key={factor}>{factor}</li>) ?? <li>ยังไม่มีข้อมูล</li>}</ul><h2>เป้าหมายของคุณ</h2><ul>{dashboard.goals.map((goal) => <li key={goal.id}>{goal.title}</li>)}</ul><h2>บันทึกล่าสุด</h2><p>{dashboard.dailyChecks[0] ? `ความมั่นใจ ${dashboard.dailyChecks[0].confidence}/10` : "ยังไม่มีบันทึก"}</p></>}</main>; }
function EmergencyPage() { return <main><h1>สัญญาณเตือน BE-FAST</h1><p><strong>หากมีอาการทางระบบประสาทเฉียบพลัน ให้โทร 1669 หรือเข้าสู่ระบบบริการฉุกเฉินทันที</strong></p><ul><li>B — การทรงตัวผิดปกติ</li><li>E — ตามองเห็นผิดปกติ</li><li>F — ใบหน้าเบี้ยว</li><li>A — แขนขาอ่อนแรง</li><li>S — พูดไม่ชัด</li><li>T — เวลา: รีบขอความช่วยเหลือทันที</li></ul><p>หน้านี้ให้ข้อมูลเพื่อการตระหนักรู้ ไม่ใช่เครื่องมือวินิจฉัยโรค</p><Link to="/participant">กลับหน้าหลัก</Link></main>; }
function GoalPage() { const [message, setMessage] = useState(""); async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const f = new FormData(event.currentTarget); try { await api("/api/participant/goals", { method: "POST", body: JSON.stringify({ title: f.get("title"), behavior: f.get("behavior"), frequency: Number(f.get("frequency")), targetDate: f.get("targetDate") }) }); setMessage("บันทึกเป้าหมายแล้ว"); } catch (e) { setMessage(e instanceof Error ? e.message : "บันทึกไม่สำเร็จ"); } } return <main><h1>สร้างเป้าหมาย SMART</h1><form onSubmit={submit}><label>เป้าหมาย<input name="title" required minLength={3} /></label><label>พฤติกรรม<input name="behavior" required minLength={3} /></label><label>ความถี่ต่อสัปดาห์<input name="frequency" type="number" min="1" required /></label><label>วันที่เป้าหมาย<input name="targetDate" type="date" required /></label><button>บันทึกเป้าหมาย</button></form>{message && <p>{message}</p>}<Link to="/participant">กลับหน้าหลัก</Link></main>; }
function DailyCheckPage() { const [message, setMessage] = useState(""); async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); try { await api("/api/participant/daily-checks", { method: "POST", body: JSON.stringify({ checkDate: new Date().toISOString().slice(0, 10), confidence: Number(form.get("confidence")), activityMinutes: Number(form.get("activityMinutes")), note: String(form.get("note") || "") }) }); setMessage("บันทึกแล้ว"); } catch (e) { setMessage(e instanceof Error ? e.message : "บันทึกไม่สำเร็จ"); } } return <main><h1>บันทึกประจำวัน</h1><form onSubmit={submit}><label>ความมั่นใจ<input name="confidence" type="number" min="0" max="10" required /></label><label>กิจกรรม (นาที)<input name="activityMinutes" type="number" min="0" /></label><label>หมายเหตุ<textarea name="note" /></label><button>บันทึกวันนี้</button></form>{message && <p>{message}</p>}<Link to="/participant">กลับหน้าหลัก</Link></main>; }
type CaseloadParticipant = { id: string; user: { displayName: string; email: string }; dailyChecks: { checkDate: string; confidence: number }[]; followUps: { point: string; dueDate: string; completedAt: string | null }[] };
function SignOutButton() { const { logout } = useAuth(); return <button onClick={() => void logout()}>ออกจากระบบ</button>; }
function NurseHome() { const [participants, setParticipants] = useState<CaseloadParticipant[]>([]); const [error, setError] = useState(""); useEffect(() => { void api<{ participants: CaseloadParticipant[] }>("/api/nurse/caseload").then(({ participants }) => setParticipants(participants)).catch((e) => setError(e.message)); }, []); return <main><h1>ผู้เข้าร่วมที่ดูแล</h1><SignOutButton />{error && <p role="alert">{error}</p>}{participants.length === 0 ? <p>ยังไม่มีผู้เข้าร่วมที่ได้รับมอบหมาย</p> : <table><thead><tr><th>ชื่อ</th><th>อีเมล</th><th>บันทึกล่าสุด</th><th>ติดตามผล</th></tr></thead><tbody>{participants.map((p) => <tr key={p.id}><td><Link to={`/nurse/participants/${p.id}`}>{p.user.displayName}</Link></td><td>{p.user.email}</td><td>{p.dailyChecks[0] ? `${p.dailyChecks[0].confidence}/10` : "ยังไม่มี"}</td><td>{p.followUps.filter((f) => !f.completedAt).length ? "มีนัดติดตาม" : "ครบแล้ว"}</td></tr>)}</tbody></table>}</main>; }
function NurseParticipantPage() { const { participantId = "" } = useParams(); const [participant, setParticipant] = useState<any>(null); const [message, setMessage] = useState(""); useEffect(() => { void api<{ participant: any }>(`/api/nurse/participants/${participantId}`).then(({ participant }) => setParticipant(participant)).catch((e) => setMessage(e.message)); }, [participantId]); async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const body = String(new FormData(event.currentTarget).get("body")); try { await api(`/api/nurse/participants/${participantId}/feedback`, { method: "POST", body: JSON.stringify({ body }) }); setMessage("ส่ง feedback แล้ว"); event.currentTarget.reset(); } catch (e) { setMessage(e instanceof Error ? e.message : "ส่งไม่สำเร็จ"); } } return <main><h1>รายละเอียดผู้เข้าร่วม</h1>{!participant ? <p>กำลังโหลดข้อมูล…</p> : <><p>{participant.user.displayName}</p><h2>เป้าหมาย</h2><ul>{participant.goals.map((goal: any) => <li key={goal.id}>{goal.title}</li>)}</ul><h2>บันทึกล่าสุด</h2><p>{participant.dailyChecks[0] ? `ความมั่นใจ ${participant.dailyChecks[0].confidence}/10` : "ยังไม่มีบันทึก"}</p><h2>ส่ง feedback</h2><form onSubmit={submit}><label>ข้อความ feedback<textarea name="body" minLength={3} required /></label><button>ส่ง feedback</button></form></>}{message && <p role="alert">{message}</p>}<p><Link to="/nurse">กลับรายชื่อ</Link></p></main>; }
type AdminUser = { id: string; email: string; displayName: string; role: "PARTICIPANT" | "NURSE" | "ADMIN"; isActive: boolean; participant: { id: string } | null };
function AdminHome() { const [users, setUsers] = useState<AdminUser[]>([]); const [error, setError] = useState(""); const [nurseId, setNurseId] = useState(""); const [participantId, setParticipantId] = useState(""); const reload = () => api<{ users: AdminUser[] }>("/api/admin/users").then(({ users }) => setUsers(users)).catch((e) => setError(e.message)); useEffect(() => { void reload(); }, []); const nurses = users.filter((u) => u.role === "NURSE"); const participants = users.filter((u) => u.role === "PARTICIPANT" && u.participant); async function assign() { try { await api("/api/admin/assignments", { method: "POST", body: JSON.stringify({ nurseId, participantId }) }); setError("บันทึกการมอบหมายแล้ว"); } catch (e) { setError(e instanceof Error ? e.message : "บันทึกไม่สำเร็จ"); } } return <main><h1>จัดการระบบ</h1><SignOutButton />{error && <p role="alert">{error}</p>}<h2>ผู้ใช้</h2><table><thead><tr><th>ชื่อ</th><th>อีเมล</th><th>บทบาท</th><th>สถานะ</th></tr></thead><tbody>{users.map((u) => <tr key={u.id}><td>{u.displayName}</td><td>{u.email}</td><td>{u.role}</td><td>{u.isActive ? "ใช้งาน" : "ปิดใช้งาน"}</td></tr>)}</tbody></table><h2>มอบหมายพยาบาล</h2><label>พยาบาล<select value={nurseId} onChange={(e) => setNurseId(e.target.value)}><option value="">เลือกพยาบาล</option>{nurses.map((u) => <option value={u.id} key={u.id}>{u.displayName}</option>)}</select></label><label>ผู้เข้าร่วม<select value={participantId} onChange={(e) => setParticipantId(e.target.value)}><option value="">เลือกผู้เข้าร่วม</option>{participants.map((u) => <option value={u.participant!.id} key={u.id}>{u.displayName}</option>)}</select></label><button disabled={!nurseId || !participantId} onClick={() => void assign()}>บันทึกการมอบหมาย</button></main>; }
export function App() { return <Routes><Route path="/login" element={<LoginPage />} /><Route path="/participant" element={<RoleRoute roles={["PARTICIPANT"]}><ParticipantHome /></RoleRoute>} /><Route path="/participant/daily-check" element={<RoleRoute roles={["PARTICIPANT"]}><DailyCheckPage /></RoleRoute>} /><Route path="/participant/goals/new" element={<RoleRoute roles={["PARTICIPANT"]}><GoalPage /></RoleRoute>} /><Route path="/participant/emergency" element={<RoleRoute roles={["PARTICIPANT"]}><EmergencyPage /></RoleRoute>} /><Route path="/nurse" element={<RoleRoute roles={["NURSE"]}><NurseHome /></RoleRoute>} /><Route path="/nurse/participants/:participantId" element={<RoleRoute roles={["NURSE"]}><NurseParticipantPage /></RoleRoute>} /><Route path="/admin" element={<RoleRoute roles={["ADMIN"]}><AdminHome /></RoleRoute>} /><Route path="*" element={<LoginPage />} /></Routes>; }
