import { Link, Route, Routes } from "react-router-dom";
import { useEffect, useState } from "react";
import { RoleRoute } from "../components/RoleRoute";
import { LoginPage } from "../features/auth/LoginPage";
import { useAuth } from "../lib/auth";
import { api } from "../lib/api";

function ParticipantHome() { const { user, logout } = useAuth(); return <main><h1>แผนดูแลตนเอง</h1><p>ยินดีต้อนรับ {user?.displayName}</p><Link to="/participant/emergency">สัญญาณฉุกเฉิน BE-FAST</Link><button onClick={() => void logout()}>ออกจากระบบ</button></main>; }
type CaseloadParticipant = { id: string; user: { displayName: string; email: string }; dailyChecks: { checkDate: string; confidence: number }[]; followUps: { point: string; dueDate: string; completedAt: string | null }[] };
function NurseHome() { const [participants, setParticipants] = useState<CaseloadParticipant[]>([]); const [error, setError] = useState(""); useEffect(() => { void api<{ participants: CaseloadParticipant[] }>("/api/nurse/caseload").then(({ participants }) => setParticipants(participants)).catch((e) => setError(e.message)); }, []); return <main><h1>ผู้เข้าร่วมที่ดูแล</h1>{error && <p role="alert">{error}</p>}{participants.length === 0 ? <p>ยังไม่มีผู้เข้าร่วมที่ได้รับมอบหมาย</p> : <table><thead><tr><th>ชื่อ</th><th>อีเมล</th><th>บันทึกล่าสุด</th><th>ติดตามผล</th></tr></thead><tbody>{participants.map((p) => <tr key={p.id}><td>{p.user.displayName}</td><td>{p.user.email}</td><td>{p.dailyChecks[0] ? `${p.dailyChecks[0].confidence}/10` : "ยังไม่มี"}</td><td>{p.followUps.filter((f) => !f.completedAt).length ? "มีนัดติดตาม" : "ครบแล้ว"}</td></tr>)}</tbody></table>}</main>; }
type AdminUser = { id: string; email: string; displayName: string; role: "PARTICIPANT" | "NURSE" | "ADMIN"; isActive: boolean; participant: { id: string } | null };
function AdminHome() { const [users, setUsers] = useState<AdminUser[]>([]); const [error, setError] = useState(""); const [nurseId, setNurseId] = useState(""); const [participantId, setParticipantId] = useState(""); const reload = () => api<{ users: AdminUser[] }>("/api/admin/users").then(({ users }) => setUsers(users)).catch((e) => setError(e.message)); useEffect(() => { void reload(); }, []); const nurses = users.filter((u) => u.role === "NURSE"); const participants = users.filter((u) => u.role === "PARTICIPANT" && u.participant); async function assign() { try { await api("/api/admin/assignments", { method: "POST", body: JSON.stringify({ nurseId, participantId }) }); setError("บันทึกการมอบหมายแล้ว"); } catch (e) { setError(e instanceof Error ? e.message : "บันทึกไม่สำเร็จ"); } } return <main><h1>จัดการระบบ</h1>{error && <p role="alert">{error}</p>}<h2>ผู้ใช้</h2><table><thead><tr><th>ชื่อ</th><th>อีเมล</th><th>บทบาท</th><th>สถานะ</th></tr></thead><tbody>{users.map((u) => <tr key={u.id}><td>{u.displayName}</td><td>{u.email}</td><td>{u.role}</td><td>{u.isActive ? "ใช้งาน" : "ปิดใช้งาน"}</td></tr>)}</tbody></table><h2>มอบหมายพยาบาล</h2><label>พยาบาล<select value={nurseId} onChange={(e) => setNurseId(e.target.value)}><option value="">เลือกพยาบาล</option>{nurses.map((u) => <option value={u.id} key={u.id}>{u.displayName}</option>)}</select></label><label>ผู้เข้าร่วม<select value={participantId} onChange={(e) => setParticipantId(e.target.value)}><option value="">เลือกผู้เข้าร่วม</option>{participants.map((u) => <option value={u.participant!.id} key={u.id}>{u.displayName}</option>)}</select></label><button disabled={!nurseId || !participantId} onClick={() => void assign()}>บันทึกการมอบหมาย</button></main>; }
export function App() { return <Routes><Route path="/login" element={<LoginPage />} /><Route path="/participant" element={<RoleRoute roles={["PARTICIPANT"]}><ParticipantHome /></RoleRoute>} /><Route path="/nurse" element={<RoleRoute roles={["NURSE"]}><NurseHome /></RoleRoute>} /><Route path="/admin" element={<RoleRoute roles={["ADMIN"]}><AdminHome /></RoleRoute>} /><Route path="*" element={<LoginPage />} /></Routes>; }
